version: '3.7'

services:
  db:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=9mREsvXDs9Gk89Ef
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./resources:/docker-entrypoint-initdb.d